# Generated by Django 5.1.1 on 2024-11-19 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='kategoriya nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=77, verbose_name='ovqat nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='ovqat haqida')),
                ('price', models.IntegerField(max_length=8, verbose_name='ovqat narxi')),
                ('is_aviable', models.BooleanField(default=True, verbose_name='mavjudligi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Foods', to='foods.category', verbose_name='qaysi kategoriyaga tegishliligi')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=22, verbose_name='buyurtmachi nomi')),
                ('quantity', models.PositiveIntegerField(verbose_name='miqdori')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='buyurtma vaqti')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='foods.food', verbose_name='qaysi ovqatga buyurtmai')),
            ],
        ),
    ]
