# Generated by Django 5.1.1 on 2024-11-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.IntegerField(verbose_name='ovqat narxi'),
        ),
    ]
