# Generated by Django 5.1.1 on 2024-11-26 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_alter_food_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='izoh')),
                ('author', models.CharField(max_length=22, verbose_name='izhoh yozganni ismi')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='yozilgan vaqti')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='foods.food', verbose_name='qaysi ovqatga izoh')),
            ],
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
